# syntax=docker/dockerfile:1

# Debian GNU/Linux 12 (bookworm)
FROM golang:1.21.1

WORKDIR /app

RUN apt-get update
RUN apt-get install vim tree -y

RUN git clone --recursive https://github.com/scottfeldman/tinygo.git
WORKDIR /app/tinygo
RUN git checkout net-submodule-netdev3
RUN git submodule update --init
RUN echo 'deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-15 main' | tee /etc/apt/sources.list.d/llvm.list
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN apt-get update
RUN apt-get install clang-15 llvm-15-dev lld-15 libclang-15-dev -y
RUN go install
RUN make llvm-source
RUN make gen-device

WORKDIR /app
##RUN git clone https://github.com/tinygo-org/tinygo-drivers.git drivers
RUN git clone https://github.com/scottfeldman/tinygo-drivers.git drivers
WORKDIR /app/drivers
#RUN git checkout scottfeldman-netdev3
RUN git checkout netdev3

WORKDIR /app
RUN go work init
RUN go work use tinygo
RUN go work use drivers

RUN apt-get install avrdude -y

#WORKDIR /app/tinygo
#RUN make test

#WORKDIR /app/drivers
#RUN make test
