#!/bin/bash

CD=`pwd`
go build -o gps main.go

cat << EOF > /tmp/gps.service
[Unit]
Description=Gps
ConditionPathExists=$CD/gps
After=network.target
 
[Service]
Type=simple
User=pi

WorkingDirectory=$CD
ExecStart=$CD/gps

Restart=on-failure
RestartSec=1

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=gps

[Install]
WantedBy=multi-user.target
EOF

sudo cp /tmp/gps.service /lib/systemd/system/gps.service
sudo systemctl daemon-reload
sudo systemctl enable gps
sudo systemctl start gps
