#!/bin/bash

APP="gps"
DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${DIR}

go build -o ${APP} main.go

cat << EOF > /tmp/${APP}.service
[Unit]
Description=Gps
ConditionPathExists=${DIR}/${APP}
After=network.target
 
[Service]
Type=simple
User=pi

WorkingDirectory=${DIR}
ExecStart=${DIR}/${APP}

Restart=on-failure
RestartSec=1

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=${APP}

[Install]
WantedBy=multi-user.target
EOF

cat << EOF > /tmp/${APP}.conf
if \$programname == '${APP}' then
/var/log/${APP}.log
& stop
EOF

sudo cp /tmp/${APP}.service /lib/systemd/system/${APP}.service
sudo cp /tmp/${APP}.conf /etc/rsyslog.d/${APP}.conf

sudo systemctl daemon-reload
sudo systemctl enable ${APP}
sudo systemctl restart rsyslog.service
sudo systemctl restart ${APP}
