#!/bin/bash

CD=`pwd`
go build -o relays main.go

cat << EOF > /tmp/relays.service
[Unit]
Description=Gps
ConditionPathExists=$CD/relays
After=network.target
 
[Service]
Type=simple
User=pi

WorkingDirectory=$CD
ExecStart=$CD/relays

Restart=on-failure
RestartSec=1

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=relays

[Install]
WantedBy=multi-user.target
EOF

sudo cp /tmp/relays.service /lib/systemd/system/relays.service
sudo systemctl daemon-reload
sudo systemctl enable relays
sudo systemctl start relays
