name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Integration Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Extract Go version from go.mod
      - name: Extract Go Version
        id: go-version
        run: |
          GO_VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "version=$GO_VERSION" >> $GITHUB_OUTPUT

      # Set up Go using the extracted version
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-version.outputs.version }}

      # Install TinyGo
      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.36.0/tinygo_0.36.0_amd64.deb
          sudo dpkg -i tinygo_0.36.0_amd64.deb

      # Run go generate to build required binaries
      - name: Generate Binaries
        run: go generate ./...

      # Run integration tests with coverage
      - name: Run Integration Tests
        run: |
          go test -v -coverpkg=./pkg/... -coverprofile=coverage.txt ./test/...

      # Display coverage in logs
      - name: Show Coverage
        run: go tool cover -func=coverage.txt

      # Upload coverage to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: merliot/hub
